export const historyDepth = 336;
export const domain = "https://pioneer.joystreamstats.live";
export const wsLocation = "wss://olympia.joystreamstats.live/rpc";
export const apiLocation = "https://joystreamstats.live/api"
export const socketLocation = "/socket.io"
export const hydraLocation = "https://hydra.joystream.org/graphql"
export const queryNode= "https://hydra.joystream.org/graphql"
//export const alternativeBackendApis = "http://localhost:3000"
export const alternativeBackendApis = "https://validators.joystreamstats.live"
export const tasksEndpoint = "https://api.joystreamstats.live/tasks"
// export const tasksEndpoint = "http://localhost:3500/tasks"