export const historyDepth = 336;
export const domain = "https://pioneer.joystreamstats.live";
//export const wsLocation = "wss://joystreamstats.live:9945";
export const wsLocation = "wss://rpc.joystream.org:9944";
export const apiLocation = "https://api.joystreamstats.live/api"
export const socketLocation = "/socket.io"
export const hydraLocation = "https://hydra.joystream.org/graphql"
// export const queryNode= "https://tiguan08.com/graphql"
// export const queryNode= "https://hydra.joystream.org/graphql"
export const queryNode= "https://query.joystream.org/graphql"
//export const alternativeBackendApis = "http://localhost:3000"
export const alternativeBackendApis = "https://validators.joystreamstats.live"
export const tasksEndpoint = "https://api.joystreamstats.live/tasks"
// export const tasksEndpoint = "http://localhost:3500/tasks"