import { domain } from "./config";
import queries from "./queries";

export const initialState = {
  log: [],
  assets: [],
  connected: false,
  faq: [],
  fetching: "",
  tasks: 0,
  blocks: [],
  nominators: [],
  validators: [],
  mints: [],
  channels: [],
  posts: [],
  councils: [],
  election: {
    applicants: [],
    votes: [],
    councilSize: 20,
  },
  categories: [],
  threads: [],
  proposals: [],
  domain,
  members: [],
  providers: [],
  reports: {},
  stakes: {},
  stashes: [],
  stars: {},
  hideFooter: true,
  hidden: ["ExtrinsicSuccess"],
  syncEvents: false,
  showStatus: false,
  editKpi: false,
  status: { era: 0, block: { id: 0, era: 0, timestamp: 0, duration: 6 } },
  groups: [],
  openings: {},
  rewardPoints: {
    total: 0,
    eraTotals: {},
    validators: {},
  },
  media: {},
  queries,
  queriesUpdated: {},
  notes: { index: "Notes are automatically saved in your browser." },
  note: "index",
  showNotes: false,
  settings: {
    connectApi: false,
    connectSocket: true,
    queryInterval: 60,
    saveInterval: 10,
    theme: "light",
    expandNotes: false,
    useStorage: true,
    searches: [],
    keysOfInterest: [],
    useSidebar: true,
    showLog: false,
    showNotes: false,
  },
};
