import { domain } from "./config";

export const initialState = {
  assets: [],
  connected: false,
  faq: [],
  fetching: "",
  tasks: 0,
  blocks: [],
  nominators: [],
  validators: [],
  mints: [],
  channels: [],
  posts: [],
  councils: [],
  election: {
    applicants: [],
    votes: [],
    councilSize: 20,
  },
  categories: [],
  threads: [],
  proposals: [],
  domain,
  members: [],
  providers: [],
  reports: {},
  stakes: {},
  stashes: [],
  stars: {},
  hideFooter: true,
  showStatus: false,
  editKpi: false,
  status: { era: 0, block: { id: 0, era: 0, timestamp: 0, duration: 6 } },
  groups: [],
  openings: {},
  rewardPoints: {
    total: 0,
    eraTotals: {},
    validators: {},
  },
  blocks: []
};
